version: '3'

services:
  postgresql:
    container_name: Postgresql-postgres-root
    image: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgresql
    volumes:
       - postgresql:/data/postgresql
    ports:
      - "5432:5432"
    networks:
      - postgresql
    restart: unless-stopped
  
  pgadmin:
    container_name: PgAdmin-deligans-at-gmail.com-root
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: deligans@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgresql
    restart: unless-stopped

networks:
  postgresql:
    driver: bridge

volumes:
    postgresql:
    pgadmin: